# Generated by Django 4.0.4 on 2022-05-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0002_carmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbrand',
            old_name='name',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='name',
            new_name='model_name',
        ),
    ]
